package Index;
/*************************************************************************
 * 
 *	Author: Zishan Qin & Yan Wang 
 *	
 *  Project2: Index
 *  
 *  Implementation choice: B+ tree
 *  
 *  Data source: NSF Research Awards Abstracts 1990-2003(ICS Department, School of Computer Science, UCI, Irvine CA, 92697, USA),
 *  part3-a list of words for indexing the bag-of-word data.
 *
 *************************************************************************/
/**
 * PutClient is used for simulating Putting operation generated by users
 * @param <Key>
 * @param <Value>
 */
public class PutClient <Key extends Comparable<Key>, Value>implements Runnable{
	   private Thread putThread;
	   private String threadName;
	   private Key key;
	   private Value value;
	   private BTree btr;
	   
	   PutClient( String name, BTree btree, Key key, Value value){
	       threadName = name;
	       this.key = key;
	       this.value=value;
	       putThread = new Thread (this, threadName);
	       putThread.start ();

	   }
	   public void run() {
			btr.put(key,value);	
        		System.out.println(threadName+"  put value"+value+" with key"+ key);
        	
	   }

}
